name: base
channels:
  - defaults
dependencies:
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astroid=2.14.2
  - asttokens=2.0.5
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - boltons=23.0.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - certifi=2023.11.17
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.1.2
  - conda=23.7.4
  - conda-content-trust=0.1.3
  - conda-libmamba-solver=23.5.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.7
  - entrypoints=0.4
  - executing=0.8.3
  - fmt=9.1.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - isort=5.9.3
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=1.23.4
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - lerc=3.0
  - libarchive=3.6.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.2.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libiconv=1.16
  - libllvm14=14.0.6
  - libmamba=1.5.1
  - libmambapy=1.5.1
  - libnghttp2=1.52.0
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - llvm-openmp=14.0.6
  - lxml=4.9.3
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mistune=0.8.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - mysql=5.7.24
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openjpeg=2.4.0
  - openssl=3.0.12
  - packaging=23.1
  - pandas=2.1.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.1.2
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pygments=2.15.1
  - pylint=2.16.2
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - ruamel.yaml=0.17.21
  - send2trash=1.8.0
  - setuptools=67.8.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomlkit=0.11.1
  - toolz=0.12.0
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - wrapt=1.14.1
  - xz=5.4.2
  - y-py=0.5.9
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
prefix: /Users/sharonwang/miniconda3
